server:
  port: 8083

spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            application-id: kafka-stream-demo
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.springframework.kafka.support.serializer.JsonSerde
          bindings:
            customEventIn:
              consumer:
                application-id: custom-event-stream
            customEventOut:
              producer:
                application-id: custom-event-stream
          #time-window:
          #  advance-by: 10000
        binder:
          brokers: localhost:9092
      bindings:
        eventIn:
          destination: nscevent
          group: nsceventGroup
        customEventIn:
          destination: nsccustomevent
          group: customEventGroup
        eventOut:
          destination: nscevent
        customEventOut:
          destination: nsccustomevent
